# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_word', models.CharField(max_length=250)),
                ('display_word', models.CharField(max_length=250)),
                ('alphabet_key', models.CharField(max_length=250)),
            ],
        ),
    ]
