# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_auto_20190423_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameapp',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
