# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_auto_20190426_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameapp',
            name='no_of_tries',
            field=models.IntegerField(null=True),
        ),
    ]
